api:
  name: apicurio-studio-api
  image: apicurio/apicurio-studio-api
  jvmArgs: -Djava.net.preferIPv4Stack=true
  port: 8091
  imagePullPolicy: IfNotPresent
  extraVolumes: []

ui:
  name: apicurio-studio-ui
  image: apicurio/apicurio-studio-ui
  jvmArgs: -Djava.net.preferIPv4Stack=true
  port: 8093
  imagePullPolicy: IfNotPresent
  channelNameRegex: ([^{}\/]*(\{[a-zA-Z_][0-9a-zA-Z_]*\})?)+
  hostname: http://34.72.50.98:8093
  extraVolumes: []
  logout:
    redirect:
      uri: "/"
  hub:
    api:
      # url to hub api
      url: null
  editing:
    # url to editing
    url: null
  feature:
    microcks: false

ws:
  name: apicurio-studio-ws
  image: apicurio/apicurio-studio-ws
  jvmArgs: -Djava.net.preferIPv4Stack=true
  port: 8092
  imagePullPolicy: IfNotPresent
  extraVolumes: []

database:
  name: apicurio-studio-db
  image: percona:5.7
  port: 3306
  imagePullPolicy: IfNotPresent
  initialize: true
  driver: mysql
  type: mysql5
  url: jdbc:mysql://apicurio-studio-db:3306/apicuriodb
  schema: apicuriodb
  #default passwords and user
  password: apicuriodb
  rootPassword: apicuriodb
  user: apicuriodb
  extraVolumes: []

uiFeatureShareForEveryone: true
loggingEnabled: false

#Configure microcks application
microcks:
  api:
    # url to mickrocks application
    url: http://MICROCKS_URL/api
  client:
    id: microcks-serviceaccount
    #default secret
    secret: apicuriomr

#Configure keycloak application
keycloak:
  # url to keycloak app
  url: http://35.232.47.140:8080/auth
  realm: apicurio
  client:
    id: apicurio-studio
    #default secret
    secret: apicuriokc
